### ISSUE TITLE
Option to change target server

### ISSUE THREAD

**Issue by Altiano** [amio/measurement-protocol#1]
Direct request to google can be blocked by ad-blocks,
This can be solved with using proxy server.

**Comment by amio** [comment]
There's an extra `config` argument for `measure()` you may use for changing target server:

```js
measure('UA-123456-12', {}, { server: 'https://www.google-analytics.com/debug' })
```

Consider this api experimental. It makes the second argument necessary, even when we don't need one, I wonder if there's a better way for this.

**Comment by Altiano** [comment]
Yes, I actually just found out about the `server` option after looking at the source code.
And I think, you don't need to make the parameter required.
It is to be expected because it is to be used for google analytics.

**Comment by amio** [comment]
I mean the second argument (that `{}`) in `measure('UA-123456-12', {}, { server: 'xxx' })`  😄
