### ISSUE TITLE
Missing ds parameter

### ISSUE THREAD

**Issue by Altiano** [amio/measurement-protocol#2]
https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ds

**Comment by amio** [comment]
For unlisted params, you may use `.set({ ds: 'web' })` to append it before `.send()`, or:

```js
const tracker = measure('UA-XXXXX-XX', { ds: 'web' })

tracker.pageview({...}).send()
```

**Comment by Altiano** [comment]
Yes, thank you.
I just need to remove the typescript warning with @ts-ignore.

**Comment by amio** [comment]
We have complete type annotation for measurement params now:

![image](https://user-images.githubusercontent.com/215282/79682803-d83f1580-8257-11ea-8816-5dd4a4cfdf57.png)
